config/routes.rb
Rails.application.routes.draw do
  root 'top#index'
  devise_for :users
  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
  end

  resources :teams, only: %i() do
    resources :categories, only: %i(index) do
      resources :posts, only: %i(new create), module: :categories
    end
  end

  resources :posts, only: %i(show new create) do
    resources :comments, only: %i(create destroy)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :comments, dependent: :destroy
  has_one :team, through: :category

  validates :title, presence: true, length: { maximum: 30 }
  validates :content, presence: true, length: { maximum: 400 }

  scope :accessible, ->(user) do
    Post.joins(category: :team).where(teams: { id: user.teams.ids })
  end

  def invalid_category?
    !user.teams.exists?(id: category.team.id)
  end
end

app/controllers/categories/posts_controller.rb
class Categories::PostsController < ApplicationController
  before_action :set_team, only: %i[new create]
  before_action :set_category, only: %i[new create]

  def new
    @post = @category.posts.build
  end

  def create
    @post = @category.posts.build(post_params)
    @post.user = current_user

    if @post.save
      redirect_to post_path(@post), notice: '投稿を作成しました'
    else
      render :new
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :content)
  end

  def set_team
    @team = current_user.teams.find(params[:team_id])
  end

  def set_category
    @category = @team.categories.find(params[:category_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def show
    @post = Post.accessible(current_user).find(params[:id])
    @comment = @post.comments.build
  end

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)
    render status: bad_request if @post.category && @post.invalid_category?

    if @post.save
      redirect_to post_path(@post), notice: '投稿を作成しました'
    else
      render :new
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :content, :category_id)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def team_id_options
    current_user.teams
                .order(created_at: :desc)
                .map { |t| [t.name, t.id, data: { path: team_categories_path(t) }] }
  end
end

app/views/posts/_errors.html.slim
- if post.errors.any?
  p.my-2 #{post.errors.size}件のエラーがあります。
  .alert.alert-danger
    - post.errors.full_messages.each do |message|
      p.mb-0 = message

app/views/posts/_form.html.slim
= render '/posts/errors', post: @post

= form_with(model: post, local: true) do |form|
  = render '/posts/select_box', post: @post, form: form

  .form-group
    = form.label :title
    = form.text_field :title, class: "form-control"

  .form-group
    = form.label :content
    = form.text_area :content, class: "form-control"

  = form.submit "投稿する", class: "btn btn-primary"

app/views/posts/_note_form.html.slim
.form-group
  = form.label :note
  = form.text_area :note, class: "form-control", placeholder: 'この投稿への思いを書いてください！'

app/views/posts/_select_box.html.slim
= form.label :team_id

- if post.category_id.blank?
  = select :team_id, :name, team_id_options, { prompt: true }, id: 'select_team'
- else
  = select_tag :team_id, options_for_select(team_id_options, post.team.id), id: 'select_team'

= form.label :category_id, class: 'ml-3'

- if post.category_id.blank?
  = form.collection_select :category_id, [], :id, :name, { prompt: true }, id: 'select_category'
- else
  = form.collection_select :category_id, post.team.categories, :id, :name, {}, id: 'select_category'

app/views/posts/_text_form.html.slim
.form-group.mt-5
  = form.label :title
  = form.text_field :title, class: "form-control"

.form-group
  = form.label :content
  = form.text_area :content, class: "form-control"

app/views/posts/create.html.slim
h1 Posts#create
p Find me in app/views/posts/create.html.slim

app/views/posts/edit.html.slim
<ul class="nav nav-pills mb-3 mt-3" id="pills-tab" role="tablist">
  <li class="nav-item">
    <a class="nav-link active" id="pills-home-tab" data-toggle="pill" href="#pills-home" role="tab" aria-controls="pills-home" aria-selected="true">投稿の内容</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" id="pills-profile-tab" data-toggle="pill" href="#pills-profile" role="tab" aria-controls="pills-profile" aria-selected="false">思い</a>
  </li>
</ul>

= render 'posts/errors', post: @post
= render 'posts/form', team: @team, category: @category, post: @post

app/views/posts/index.html.slim
- @posts.each do |post|
    p
      = post.title
    p
      = post.discription
    p
      = post.image_url
    p
      = post.upload_file
    p
      = post.create_at

app/views/posts/new.html.slim
= form_with(model: @post, local: true) do |form|
  .mt-3
    = render 'posts/form', post: @post, form: form

app/views/posts/show.html.slim
p.mb-0
  | チーム名：
  = link_to @post.category.team.name, team_path(@post.category.team)


| 参加者：
- @post.category.team.users.each do |user|
  span.mr-3
    = image_tag 'https://picsum.photos/30/30?image=' + rand(100).to_s, class: 'rounded-circle mr-1'
    span class=member_name_class(@post, user)
      = user.name

p カテゴリ名：#{@post.category.name}
hr

.card.mt-3
  .card-header
    = @post.title
    small.ml-2
      | by #{@post.user.name}
    span.badge.badge-default 投稿日時
    small= l @post.created_at
    i.fa.fa-edit.text-primary.ml-2
    i.fa.fa-trash.text-primary.ml-2

  .card-body
    .card-text.mt-3
      = simple_format @post.content

#comments_area
  = render 'comments/list', post: @post
= render 'comments/form', post: @post, comment: @comment