config/routes.rb
Rails.application.routes.draw do
  root 'top#index'
  devise_for :users
  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
  end

  resources :teams, only: %i() do
    resources :categories, only: %i(index) do
      resources :posts, only: %i(new create), module: :categories
    end
  end

  resources :posts, only: %i(show new create) do
    resources :comments, only: %i(create destroy)
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :team
  has_many :posts, dependent: :destroy

  validates :name, presence: true, uniqueness: { scope: :team }, length: { maximum: 30 }
  validates :description, length: { maximum: 280 }

  mount_uploader :image, ImageUploader
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :content, presence: true, length: { maximum: 400 }
end

app/models/membership.rb
class Membership < ApplicationRecord
  belongs_to :team
  belongs_to :user

  validates :team_id, uniqueness: { scope: :user_id }
end

app/models/memberships.rb
class Membership < ApplicationRecord
  belongs_to :team
  belongs_to :user

  validates :team_id, presence: true
  validates :user_id, presence: true
  validates :team_id,  uniquness: { scope: :user_id }
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :comments, dependent: :destroy
  has_one :team, through: :category

  validates :title, presence: true, length: { maximum: 30 }
  validates :content, presence: true, length: { maximum: 400 }

  scope :accessible, ->(user) do
    Post.joins(category: :team).where(teams: { id: user.teams.ids })
  end

  def invalid_category?
    !user.teams.exists?(id: category.team.id)
  end
end

app/models/team.rb
class Team < ApplicationRecord
  has_many :memberships, dependent: :destroy
  has_many :users, through: :memberships
  has_many :categories, dependent: :destroy
  has_many :team_edit_rights, dependent: :destroy
  belongs_to :author, class_name: 'User',
                      foreign_key: 'user_id',
                      inverse_of: :teams

  validates :name, presence: true, uniqueness: true, length: { maximum: 30 }
  validates :description, length: { maximum: 280 }

  mount_uploader :image, ImageUploader
end

app/models/team_edit_right.rb
class TeamEditRight < ApplicationRecord
  belongs_to :team
  belongs_to :user
  validates :team_id, uniqueness: { scope: :user_id }
end

app/models/teams_user.rb
class TeamsUser < ApplicationRecord
  belongs_to :team
  belongs_to :user

  validates :team_id, presence: true
  validates :user_id, presence: true
  validates :team_id,  uniquness: { scope: :user_id }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :memberships, dependent: :destroy
  has_many :teams, through: :memberships
  has_many :posts
  has_many :comments

  validates :name, presence: true, length: { maximum: 30 }
  validates :description, length: { maximum: 280 }

  mount_uploader :image, ImageUploader

  def can_comment?(post)
    teams.exists?(id: post.category.team.id)
  end

  def can_delete_comment?(comment)
    self == comment.user
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post, only: %i[create destroy]

  def create
    @comment = @post.comments.build(comment_params)
    @comment.user = current_user
    if current_user.can_comment?(@post)
      @comment.save
    else
      render status: :forbidden
    end
  end

  def destroy
    @comment = Comment.find(params[:id])

    if current_user.can_delete_comment?(@comment)
      @comment.destroy!
    else
      render status: :forbidden
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end

  def set_post
    @post = Post.find(params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def show
    @post = Post.accessible(current_user).find(params[:id])
    @comment = @post.comments.build
  end

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)
    render status: bad_request if @post.category && @post.invalid_category?

    if @post.save
      redirect_to post_path(@post), notice: '投稿を作成しました'
    else
      render :new
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :content, :category_id)
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :set_team, only: %i[show edit update destroy]

  def new
    @team = current_user.teams.build
  end

  def create
    @team = current_user.teams.build(team_params)
    if @team.save
      redirect_to team_path(@team), notice: 'チームを作るのに成功しました'
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @team.update(team_params)
      redirect_to team_path(@team), notice: '情報を更新しました'
    else
      render :edit
    end
  end

  def destroy
    # TODO: 後でbankenによる権限付与を行う
    @team.destroy!
    redirect_to root_path, alert: 'チームを削除しました'
  end

  private

  def team_params
    params.require(:team).permit(:name, :description, :image)
  end

  def set_team
    @team = current_user.teams.find(params[:id])
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @team = Team.find(params[:team_id])
    @users = User.all
    #@users_not_in_team = User.where.not(id: @users)
  end
  def show
    # TODO あとでちゃんと条件のscopeなり何なりを作ること
    other_user = User.find(params[:id])
    @user = other_user if current_user.can_see?(other_user)
  end
end

app/helpers/alert_helper.rb
module AlertHelper
  def alert_class(key)
    if key == 'notice'
      'alert alert-info alert-dismissible fade show my-3'
    elsif key == 'alert'
      'alert alert-danger alert-dismissible fade show my-3'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flash_helper.rb
module FlashHelper
  def flash_class(key)
    if key == 'notice'
      'alert alert-info alert-dismissible fade show my-3'
    elsif key == 'alert'
      'alert alert-danger alert-dismissible fade show my-3'
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def team_id_options
    current_user.teams
                .order(created_at: :desc)
                .map { |t| [t.name, t.id, data: { path: team_categories_path(t) }] }
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def member_name_class(post, user)
    if user == post.user
      'font-weight-bold'
    elsif user == User.last
      'text-danger'
    else
      'font-weight-normal'
    end
  end
end

app/views/layouts/_header.html.slim
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        = link_to 'Dive into Share', root_path, class: 'navbar-brand'
        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#Navber" aria-controls="Navber" aria-expanded="false" aria-label="ナビゲーションの切替">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="Navber">
          <ul class="navbar-nav mr-auto">

            <li class="nav-item">
              = link_to '投稿', new_post_path, class: 'nav-link'
            </li>
            <li class="nav-item dropdown">
              <a href="#" class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                チーム作成
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="#">メニュー1</a>
                <a class="dropdown-item" href="#">メニュー2</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">その他</a>
              </div>
            </li>
            <li class="nav-item">
              <a class="nav-link disabled" href="#">マイページ</a>
            </li>
            <li class="nav-item">
              <a class="nav-link disabled" href="#">ログアウト</a>
            </li>
          </ul>

          </form>
        </div><!-- /.navbar-collapse -->
      </nav>

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | DiveIntoShare
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css"
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  body
    = render "shared/header"
    .container
      = render "shared/alert"
      = render "shared/main"
    = render "shared/footer"

app/views/shared/_alert.html.slim
.row
  .col
    - if flash
      - flash.each do |key, value|
        div class=alert_class(key) role='alert'
          = value
          button type='button' class='close' data-dismiss='alert' aria-label='Close'
            span aria-hidden='true'
              | &times;

app/views/shared/_flash.html.slim
.row
  .col
    - if flash
      - flash.each do |key, value|
        div class='#{flash_class(key)}' role='alert'
          = value
          button type='button' class='close' data-dismiss='alert' aria-label='Close'
            span aria-hidden='true'
              | &times;

app/views/shared/_footer.html.slim
footer.footer.bg-color-header
  span.text-muted.text-center
  .text-center
    |  ©️2018 DIVE INTO SHARE

app/views/shared/_header.html.slim
nav.navbar.navbar-expand-md.navbar-light.bg-color-header
  = link_to 'DIVE INTO SHARE', root_path, class: "navbar-brand"
  button.navbar-toggler[type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
   aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"]
    span.navbar-toggler-icon
  #navbarSupportedContent.collapse.navbar-collapse
    ul.navbar-nav.mr-auto
      li.nav-item
        = link_to "投稿", new_post_path, class: "btn btn-primary btn-sm"
    ul.navbar-nav
      - if user_signed_in?
        .my-auto
          li.nav-item
            span.badge.badge-pill.badge-info.mx-auto.my-auto
              | 0
        .my-auto
          li.nav-item
            i.fa.fa-bell[aria-hidden="true"]

        .my-auto
          li.nav-item
            = link_to "#{current_user.name}さん", edit_user_registration_path(current_user.id) ,class: "nav-link"
        li.nav-item
          = link_to "ログアウト", destroy_user_session_path, method: :delete ,class: "nav-link"
      - else
        li.nav-item
          = link_to 'ログイン', new_user_session_path, class: "nav-link"

app/views/shared/_main.html.slim
.row
  - if user_signed_in?
    .col-5.bg-light
      = render "shared/side_menu"
    .col-7
      = yield
  - else
    .col
      = yield

app/views/shared/_side_menu.html.slim
= link_to 'チーム作成', '#', class: 'btn btn-secondary m-3'

- if member_teams.present?
  ul.mt-4.list-style_none
    - member_teams.each do |team|
      li.mt-3
        i.fas.fa-users.mr-1
        = team.name

      ul.mt-4.list-style_none
        -team.categories.order(created_at: :desc).each do |category|
          li.mt-3
            i.fas.fa-folder.mr-1
            = category.name
            = link_to '投稿', new_team_category_post_path(team, category),
             class: 'btn btn-primary btn-sm ml-3'

          ul.mt-4.list-style_none
            - category.posts.order(created_at: :desc).each do |post|
              li.mt-3
                i.fas.fa-file-alt.mr-1
                = link_to post.title, post_path(post)